services:
  postgres:
    image: postgres:17.0
    environment:
      - POSTGRES_DB=my-app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P4ssword!
    ports:
      - 5432:5432

  backend:
    image: nhutlm1/backend:###TAG### # Replace with your Spring Boot image name
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://postgres:5432/my-app
      - JDBC_DATABASE_USERNAME=postgres
      - JDBC_DATABASE_PASSWORD=P4ssword!
    ports:
      - 8080:8080
    depends_on:
      - postgres
